micronaut:
  application:
    name: micronaut-application
  server:
    port: 8080
    context-path: /micronaut-application/v1

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://192.168.5.10:5432/native_test`}
    username: ${JDBC_USER:native_test_user}
    password: ${JDBC_PASSWORD:stdpsw951}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true